"""Create resume_analyses table

Revision ID: 7f3a19c4e201
Revises: 412c20700069
Create Date: 2026-08-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3a19c4e201'
down_revision = '412c20700069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resume_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ats_score', sa.Float(), nullable=False),
        sa.Column('matched_skills', sa.Text(), nullable=True),
        sa.Column('missing_skills', sa.Text(), nullable=True),
        sa.Column('recommendations', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
